test_fw:
  build: .
  dockerfile: Dockerfile
  restart: always
  ports:
   - "80:80"
  volumes:
   - .:/var/www
  links:
   - test_db:test_db
test_db:
  image: mysql
  command: --default-authentication-plugin=mysql_native_password
  restart: always
  ports:
   - "3306:3306"
  volumes:
   - ./dumps:/docker-entrypoint-initdb.d
  environment:
    MYSQL_ROOT_PASSWORD: sss2019